services:
  #Aplicação .net
  service.cadastro:
    image: service.cadastro
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "2195:8080"
    networks:
      - my-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: pos12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postech
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5435:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
    
networks:
  my-network: