# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build e Testes

on:
  push:
    branches: [ "main", develop ]
  pull_request:
    branches: [ "main", develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USER_DOCKER_NAME }}
        password: ${{ secrets.DOCKER_SECRET }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: ./Service/Serverless/Service.Cadastro
        push: true
        tags: '${{ secrets.USER_DOCKER_NAME }}/cadastro-tech:latest'